name: Self — YAML Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yamlfmt:
    uses: ./.github/workflows/yamlfmt.yml
    permissions:
      contents: write
      workflows: write
    with:
      auto-commit: true
