name: Self YML Formatter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  yml-formatter:
    name: YML Formatter
    uses: ./.github/workflows/yml-formatter.yml
    with:
      auto-commit: true